version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:latest

     steps:
        - checkout

        - run:
            name: deps
            command:
                apt-get install -y pdftk bibtex2html libxml2-dev libxslt1-dev libffi6 libffi-dev python-dev python-numpy python-matplotlib virtualenv

                pip install -U decorator>=4.1.0
        - run:
            name: prince
            command:
                wget https://www.princexml.com/download/prince_11.3-1_ubuntu16.04_amd64.deb
                dpkg -i prince_11.3-1_ubuntu16.04_amd64.deb
                
        - run:
            name: NPM
            command:
                 npm install MathJax-node jsdom@9.3 less

        - run:
            name: check out duckuments-dist
            command:
                mkdir -p duckuments-dist

        - run:
            name: checkout MCDP
            command: |
                git clone -b duckuments git@github.com:AndreaCensi/mcdp
                cd mcdp && python setup.py develop

        - run:
            name: checkout duckietown repository
            command: |
                git clone -b master --depth 1 git@github.com:duckietown/Software duckietown

        - run:
            name: install fonts
            command:  |
                cp -R fonts /usr/share/fonts/duckuments-fonts
                fc-cache -f -v
                fc-list | grep STIX
                fc-list | grep Symbola

        - run:
            name: Compile HTML version
            command: |
                make compile

        - run:
            name: Compile PDF version
            command: |
                make compile-pdf

        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist
