version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:6

     steps:
        - checkout

        - run:
            name: deps
            command:
                sudo apt install -y pdftk bibtex2html libxml2-dev libxslt1-dev libffi6 libffi-dev python-dev python-numpy python-matplotlib virtualenv

        - run:
            name: checkout MCDP
            command: make duckuments-dist

        - run:
            name: build
            command: |
                git clone -b duckuments git@github.com:AndreaCensi/mcdp
                cd mcdp && python setup.py develop

                make build-parallel
                vdir $PWD/catkin_ws/devel

        - run:
            name: run tests
            command: |
                mkdir -p duckuments-dist
                make compile

        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist
