version: 2
jobs:
    build:
     docker:
        - image: andreacensi/duckietown-xenial-kinetic:6

     steps:
        - checkout

        - run:
            name: deps
            command:
                apt-get install -y pdftk bibtex2html libxml2-dev libxslt1-dev libffi6 libffi-dev python-dev python-numpy python-matplotlib virtualenv
                pip install -U decorator>=4.1.0

        - run:
            name: checkoutduckuments-dist
            command: make duckuments-dist

        - run:
            name: checkout MCDP
            command: |
                git clone -b duckuments git@github.com:AndreaCensi/mcdp
                cd mcdp && python setup.py develop

        - run:
            name: run tests
            command: |
                mkdir -p duckuments-dist
                make compile

        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist
